version: 0.2

env:
  variables:
    NEXT_PUBLIC_API_URL: "http://book-management-app-prod.eba-qj8nekzp.ap-northeast-2.elasticbeanstalk.com"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd book-management-front
      - npm ci
  build:
    commands:
      - echo Frontend Build Started...
      - npm run build
artifacts:
  base-directory: book-management-front
  files:
    - '.next/**/*'
    - 'public/**/*'
    - 'package.json'
    - 'node_modules/**/*'